"""
Base classes and data structures for trading strategies.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any
import polars as pl


class SignalAction(Enum):
    """Trade signal actions."""
    BUY = "buy"
    SELL = "sell"
    SHORT = "short"
    COVER = "cover"
    HOLD = "hold"


@dataclass
class Signal:
    """
    A trading signal generated by a strategy.

    Attributes:
        timestamp: Time when signal is generated
        ticker: Stock ticker symbol
        action: Buy, sell, short, cover, or hold
        size: Number of shares (or proportion of capital if < 1)
        price: Price at signal generation (for reference)
        confidence: Optional confidence score (0-1)
        reason: Optional description of why signal was generated
        indicators: Optional dict of indicator values at signal time
    """
    timestamp: datetime
    ticker: str
    action: SignalAction
    size: float
    price: float
    confidence: Optional[float] = None
    reason: Optional[str] = None
    indicators: Optional[Dict[str, Any]] = None

    def __repr__(self):
        conf_str = f", conf={self.confidence:.2f}" if self.confidence else ""
        return (f"Signal({self.timestamp}, {self.ticker}, {self.action.value}, "
                f"size={self.size}, price=${self.price:.2f}{conf_str})")


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    All strategies must implement the generate_signals method which takes
    market data and returns a list of trading signals.
    """

    def __init__(self, name: str, params: Optional[Dict[str, Any]] = None):
        """
        Initialize strategy.

        Args:
            name: Strategy name
            params: Dictionary of strategy parameters
        """
        self.name = name
        self.params = params or {}

    @abstractmethod
    def generate_signals(self, data: pl.DataFrame) -> List[Signal]:
        """
        Generate trading signals from market data.

        Args:
            data: Polars DataFrame with OHLCV data. Expected columns:
                - timestamp: datetime
                - ticker: str
                - open, high, low, close: float
                - volume: int

        Returns:
            List of Signal objects in chronological order
        """
        pass

    def __repr__(self):
        params_str = ", ".join(f"{k}={v}" for k, v in self.params.items())
        return f"{self.__class__.__name__}({params_str})"


def validate_data(data: pl.DataFrame, required_columns: List[str]) -> None:
    """
    Validate that DataFrame has required columns.

    Args:
        data: Input DataFrame
        required_columns: List of required column names

    Raises:
        ValueError: If any required columns are missing
    """
    missing = set(required_columns) - set(data.columns)
    if missing:
        raise ValueError(f"Missing required columns: {missing}")


def calculate_vwap(data: pl.DataFrame) -> pl.DataFrame:
    """
    Calculate Volume-Weighted Average Price (VWAP).

    Args:
        data: DataFrame with 'close' and 'volume' columns

    Returns:
        DataFrame with additional 'vwap' column
    """
    return data.with_columns([
        ((pl.col("close") * pl.col("volume")).cum_sum() /
         pl.col("volume").cum_sum()).alias("vwap")
    ])


def calculate_bollinger_bands(
    data: pl.DataFrame,
    window: int = 20,
    num_std: float = 2.0
) -> pl.DataFrame:
    """
    Calculate Bollinger Bands.

    Args:
        data: DataFrame with 'close' column
        window: Rolling window size
        num_std: Number of standard deviations for bands

    Returns:
        DataFrame with additional columns:
        - bb_middle: Middle band (SMA)
        - bb_upper: Upper band
        - bb_lower: Lower band
    """
    return data.with_columns([
        pl.col("close").rolling_mean(window).alias("bb_middle"),
    ]).with_columns([
        (pl.col("bb_middle") +
         num_std * pl.col("close").rolling_std(window)).alias("bb_upper"),
        (pl.col("bb_middle") -
         num_std * pl.col("close").rolling_std(window)).alias("bb_lower"),
    ])


def calculate_relative_volume(data: pl.DataFrame, window: int = 10) -> pl.DataFrame:
    """
    Calculate relative volume (current volume vs average).

    Args:
        data: DataFrame with 'volume' column
        window: Lookback window for average volume

    Returns:
        DataFrame with additional 'rvol' column (ratio of current to avg volume)
    """
    return data.with_columns([
        (pl.col("volume") / pl.col("volume").rolling_mean(window)).alias("rvol")
    ])
